WRONG_PASSWORD = "Password is wrong! Check the password and try again."
FAILED_VALIDATION = "Parameter validation failed"
MISSING_CREDENTIALS = "Login credentials are missing! Please check them once."
STRING_REQUIRED = "username & password must be a string"
INVALID_USER = "user not found for the email you entered"